/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as SelectSocietyRouteImport } from './routes/select-society'
import { Route as authLoginRouteImport } from './routes/(auth)/login'
import { Route as AuthenticatedAnalyticsRouteImport } from './routes/_authenticated.analytics'
import { Route as AuthenticatedAnnouncementsRouteImport } from './routes/_authenticated.announcements'
import { Route as AuthenticatedDeliveriesRouteImport } from './routes/_authenticated.deliveries'
import { Route as AuthenticatedDocumentsRouteImport } from './routes/_authenticated.documents'
import { Route as AuthenticatedEmergencyRouteImport } from './routes/_authenticated.emergency'
import { Route as AuthenticatedExpectedVisitorsRouteImport } from './routes/_authenticated.expected-visitors'
import { Route as AuthenticatedFlatsRouteImport } from './routes/_authenticated.flats'
import { Route as AuthenticatedGuardRouteImport } from './routes/_authenticated.guard'
import { Route as AuthenticatedMaintenanceRouteImport } from './routes/_authenticated.maintenance'
import { Route as AuthenticatedNoticesRouteImport } from './routes/_authenticated.notices'
import { Route as AuthenticatedPaymentsRouteImport } from './routes/_authenticated.payments'
import { Route as AuthenticatedProfileRouteImport } from './routes/_authenticated.profile'
import { Route as AuthenticatedPublicComplaintsRouteImport } from './routes/_authenticated.public-complaints'
import { Route as AuthenticatedQrScannerRouteImport } from './routes/_authenticated.qr-scanner'
import { Route as AuthenticatedResidentRouteImport } from './routes/_authenticated.resident'
import { Route as AuthenticatedResidentsRouteImport } from './routes/_authenticated.residents'
import { Route as AuthenticatedSecretaryRouteImport } from './routes/_authenticated.secretary'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated.settings'
import { Route as AuthenticatedStaffRouteImport } from './routes/_authenticated.staff'
import { Route as AuthenticatedSuperadminRouteImport } from './routes/_authenticated.superadmin'
import { Route as AuthenticatedVisitorApprovalRouteImport } from './routes/_authenticated.visitor-approval'
import { Route as AuthenticatedVisitorReportsRouteImport } from './routes/_authenticated.visitor-reports'
import { Route as SocietiesSocietyIdRouteImport } from './routes/societies.$societyId'
import { Route as SocietiesNewRouteImport } from './routes/societies.new'
import { Route as AuthenticatedComplaintsIndexRouteImport } from './routes/_authenticated.complaints.index'
import { Route as AuthenticatedComplaintsNewRouteImport } from './routes/_authenticated.complaints.new'
import { Route as AuthenticatedGuardDashboardRouteImport } from './routes/_authenticated.guard.dashboard'
import { Route as AuthenticatedResidentDashboardRouteImport } from './routes/_authenticated.resident.dashboard'
import { Route as AuthenticatedSecretaryDashboardRouteImport } from './routes/_authenticated.secretary.dashboard'
import { Route as AuthenticatedSuperadminDashboardRouteImport } from './routes/_authenticated.superadmin.dashboard'
import { Route as AuthenticatedVisitorsHistoryRouteImport } from './routes/_authenticated.visitors.history'
import { Route as AuthenticatedVisitorsNewRouteImport } from './routes/_authenticated.visitors.new'
import { Route as SocietiesSocietyIdEditRouteImport } from './routes/societies.$societyId.edit'
import { Route as AuthenticatedGuardVisitorsNewRouteImport } from './routes/_authenticated.guard.visitors.new'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const SelectSocietyRoute = SelectSocietyRouteImport.update({
  id: '/select-society',
  path: '/select-society',
  getParentRoute: () => rootRouteImport,
} as any)
const authLoginRoute = authLoginRouteImport.update({
  id: '/(auth)/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAnalyticsRoute = AuthenticatedAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAnnouncementsRoute =
  AuthenticatedAnnouncementsRouteImport.update({
    id: '/announcements',
    path: '/announcements',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedDeliveriesRoute = AuthenticatedDeliveriesRouteImport.update({
  id: '/deliveries',
  path: '/deliveries',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedDocumentsRoute = AuthenticatedDocumentsRouteImport.update({
  id: '/documents',
  path: '/documents',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedEmergencyRoute = AuthenticatedEmergencyRouteImport.update({
  id: '/emergency',
  path: '/emergency',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedExpectedVisitorsRoute =
  AuthenticatedExpectedVisitorsRouteImport.update({
    id: '/expected-visitors',
    path: '/expected-visitors',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedFlatsRoute = AuthenticatedFlatsRouteImport.update({
  id: '/flats',
  path: '/flats',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedGuardRoute = AuthenticatedGuardRouteImport.update({
  id: '/guard',
  path: '/guard',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedMaintenanceRoute =
  AuthenticatedMaintenanceRouteImport.update({
    id: '/maintenance',
    path: '/maintenance',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedNoticesRoute = AuthenticatedNoticesRouteImport.update({
  id: '/notices',
  path: '/notices',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedPaymentsRoute = AuthenticatedPaymentsRouteImport.update({
  id: '/payments',
  path: '/payments',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedProfileRoute = AuthenticatedProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedPublicComplaintsRoute =
  AuthenticatedPublicComplaintsRouteImport.update({
    id: '/public-complaints',
    path: '/public-complaints',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedQrScannerRoute = AuthenticatedQrScannerRouteImport.update({
  id: '/qr-scanner',
  path: '/qr-scanner',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedResidentRoute = AuthenticatedResidentRouteImport.update({
  id: '/resident',
  path: '/resident',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedResidentsRoute = AuthenticatedResidentsRouteImport.update({
  id: '/residents',
  path: '/residents',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedSecretaryRoute = AuthenticatedSecretaryRouteImport.update({
  id: '/secretary',
  path: '/secretary',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedStaffRoute = AuthenticatedStaffRouteImport.update({
  id: '/staff',
  path: '/staff',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedSuperadminRoute = AuthenticatedSuperadminRouteImport.update({
  id: '/superadmin',
  path: '/superadmin',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedVisitorApprovalRoute =
  AuthenticatedVisitorApprovalRouteImport.update({
    id: '/visitor-approval',
    path: '/visitor-approval',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedVisitorReportsRoute =
  AuthenticatedVisitorReportsRouteImport.update({
    id: '/visitor-reports',
    path: '/visitor-reports',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const SocietiesSocietyIdRoute = SocietiesSocietyIdRouteImport.update({
  id: '/societies/$societyId',
  path: '/societies/$societyId',
  getParentRoute: () => rootRouteImport,
} as any)
const SocietiesNewRoute = SocietiesNewRouteImport.update({
  id: '/societies/new',
  path: '/societies/new',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedComplaintsIndexRoute =
  AuthenticatedComplaintsIndexRouteImport.update({
    id: '/complaints/',
    path: '/complaints/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedComplaintsNewRoute =
  AuthenticatedComplaintsNewRouteImport.update({
    id: '/complaints/new',
    path: '/complaints/new',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedGuardDashboardRoute =
  AuthenticatedGuardDashboardRouteImport.update({
    id: '/dashboard',
    path: '/dashboard',
    getParentRoute: () => AuthenticatedGuardRoute,
  } as any)
const AuthenticatedResidentDashboardRoute =
  AuthenticatedResidentDashboardRouteImport.update({
    id: '/dashboard',
    path: '/dashboard',
    getParentRoute: () => AuthenticatedResidentRoute,
  } as any)
const AuthenticatedSecretaryDashboardRoute =
  AuthenticatedSecretaryDashboardRouteImport.update({
    id: '/dashboard',
    path: '/dashboard',
    getParentRoute: () => AuthenticatedSecretaryRoute,
  } as any)
const AuthenticatedSuperadminDashboardRoute =
  AuthenticatedSuperadminDashboardRouteImport.update({
    id: '/dashboard',
    path: '/dashboard',
    getParentRoute: () => AuthenticatedSuperadminRoute,
  } as any)
const AuthenticatedVisitorsHistoryRoute =
  AuthenticatedVisitorsHistoryRouteImport.update({
    id: '/visitors/history',
    path: '/visitors/history',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedVisitorsNewRoute =
  AuthenticatedVisitorsNewRouteImport.update({
    id: '/visitors/new',
    path: '/visitors/new',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const SocietiesSocietyIdEditRoute = SocietiesSocietyIdEditRouteImport.update({
  id: '/edit',
  path: '/edit',
  getParentRoute: () => SocietiesSocietyIdRoute,
} as any)
const AuthenticatedGuardVisitorsNewRoute =
  AuthenticatedGuardVisitorsNewRouteImport.update({
    id: '/visitors/new',
    path: '/visitors/new',
    getParentRoute: () => AuthenticatedGuardRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/select-society': typeof SelectSocietyRoute
  '/login': typeof authLoginRoute
  '/analytics': typeof AuthenticatedAnalyticsRoute
  '/announcements': typeof AuthenticatedAnnouncementsRoute
  '/deliveries': typeof AuthenticatedDeliveriesRoute
  '/documents': typeof AuthenticatedDocumentsRoute
  '/emergency': typeof AuthenticatedEmergencyRoute
  '/expected-visitors': typeof AuthenticatedExpectedVisitorsRoute
  '/flats': typeof AuthenticatedFlatsRoute
  '/guard': typeof AuthenticatedGuardRouteWithChildren
  '/maintenance': typeof AuthenticatedMaintenanceRoute
  '/notices': typeof AuthenticatedNoticesRoute
  '/payments': typeof AuthenticatedPaymentsRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/public-complaints': typeof AuthenticatedPublicComplaintsRoute
  '/qr-scanner': typeof AuthenticatedQrScannerRoute
  '/resident': typeof AuthenticatedResidentRouteWithChildren
  '/residents': typeof AuthenticatedResidentsRoute
  '/secretary': typeof AuthenticatedSecretaryRouteWithChildren
  '/settings': typeof AuthenticatedSettingsRoute
  '/staff': typeof AuthenticatedStaffRoute
  '/superadmin': typeof AuthenticatedSuperadminRouteWithChildren
  '/visitor-approval': typeof AuthenticatedVisitorApprovalRoute
  '/visitor-reports': typeof AuthenticatedVisitorReportsRoute
  '/societies/$societyId': typeof SocietiesSocietyIdRouteWithChildren
  '/societies/new': typeof SocietiesNewRoute
  '/complaints/new': typeof AuthenticatedComplaintsNewRoute
  '/guard/dashboard': typeof AuthenticatedGuardDashboardRoute
  '/resident/dashboard': typeof AuthenticatedResidentDashboardRoute
  '/secretary/dashboard': typeof AuthenticatedSecretaryDashboardRoute
  '/superadmin/dashboard': typeof AuthenticatedSuperadminDashboardRoute
  '/visitors/history': typeof AuthenticatedVisitorsHistoryRoute
  '/visitors/new': typeof AuthenticatedVisitorsNewRoute
  '/societies/$societyId/edit': typeof SocietiesSocietyIdEditRoute
  '/complaints/': typeof AuthenticatedComplaintsIndexRoute
  '/guard/visitors/new': typeof AuthenticatedGuardVisitorsNewRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/select-society': typeof SelectSocietyRoute
  '/login': typeof authLoginRoute
  '/analytics': typeof AuthenticatedAnalyticsRoute
  '/announcements': typeof AuthenticatedAnnouncementsRoute
  '/deliveries': typeof AuthenticatedDeliveriesRoute
  '/documents': typeof AuthenticatedDocumentsRoute
  '/emergency': typeof AuthenticatedEmergencyRoute
  '/expected-visitors': typeof AuthenticatedExpectedVisitorsRoute
  '/flats': typeof AuthenticatedFlatsRoute
  '/guard': typeof AuthenticatedGuardRouteWithChildren
  '/maintenance': typeof AuthenticatedMaintenanceRoute
  '/notices': typeof AuthenticatedNoticesRoute
  '/payments': typeof AuthenticatedPaymentsRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/public-complaints': typeof AuthenticatedPublicComplaintsRoute
  '/qr-scanner': typeof AuthenticatedQrScannerRoute
  '/resident': typeof AuthenticatedResidentRouteWithChildren
  '/residents': typeof AuthenticatedResidentsRoute
  '/secretary': typeof AuthenticatedSecretaryRouteWithChildren
  '/settings': typeof AuthenticatedSettingsRoute
  '/staff': typeof AuthenticatedStaffRoute
  '/superadmin': typeof AuthenticatedSuperadminRouteWithChildren
  '/visitor-approval': typeof AuthenticatedVisitorApprovalRoute
  '/visitor-reports': typeof AuthenticatedVisitorReportsRoute
  '/societies/$societyId': typeof SocietiesSocietyIdRouteWithChildren
  '/societies/new': typeof SocietiesNewRoute
  '/complaints/new': typeof AuthenticatedComplaintsNewRoute
  '/guard/dashboard': typeof AuthenticatedGuardDashboardRoute
  '/resident/dashboard': typeof AuthenticatedResidentDashboardRoute
  '/secretary/dashboard': typeof AuthenticatedSecretaryDashboardRoute
  '/superadmin/dashboard': typeof AuthenticatedSuperadminDashboardRoute
  '/visitors/history': typeof AuthenticatedVisitorsHistoryRoute
  '/visitors/new': typeof AuthenticatedVisitorsNewRoute
  '/societies/$societyId/edit': typeof SocietiesSocietyIdEditRoute
  '/complaints': typeof AuthenticatedComplaintsIndexRoute
  '/guard/visitors/new': typeof AuthenticatedGuardVisitorsNewRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/select-society': typeof SelectSocietyRoute
  '/(auth)/login': typeof authLoginRoute
  '/_authenticated/analytics': typeof AuthenticatedAnalyticsRoute
  '/_authenticated/announcements': typeof AuthenticatedAnnouncementsRoute
  '/_authenticated/deliveries': typeof AuthenticatedDeliveriesRoute
  '/_authenticated/documents': typeof AuthenticatedDocumentsRoute
  '/_authenticated/emergency': typeof AuthenticatedEmergencyRoute
  '/_authenticated/expected-visitors': typeof AuthenticatedExpectedVisitorsRoute
  '/_authenticated/flats': typeof AuthenticatedFlatsRoute
  '/_authenticated/guard': typeof AuthenticatedGuardRouteWithChildren
  '/_authenticated/maintenance': typeof AuthenticatedMaintenanceRoute
  '/_authenticated/notices': typeof AuthenticatedNoticesRoute
  '/_authenticated/payments': typeof AuthenticatedPaymentsRoute
  '/_authenticated/profile': typeof AuthenticatedProfileRoute
  '/_authenticated/public-complaints': typeof AuthenticatedPublicComplaintsRoute
  '/_authenticated/qr-scanner': typeof AuthenticatedQrScannerRoute
  '/_authenticated/resident': typeof AuthenticatedResidentRouteWithChildren
  '/_authenticated/residents': typeof AuthenticatedResidentsRoute
  '/_authenticated/secretary': typeof AuthenticatedSecretaryRouteWithChildren
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/_authenticated/staff': typeof AuthenticatedStaffRoute
  '/_authenticated/superadmin': typeof AuthenticatedSuperadminRouteWithChildren
  '/_authenticated/visitor-approval': typeof AuthenticatedVisitorApprovalRoute
  '/_authenticated/visitor-reports': typeof AuthenticatedVisitorReportsRoute
  '/societies/$societyId': typeof SocietiesSocietyIdRouteWithChildren
  '/societies/new': typeof SocietiesNewRoute
  '/_authenticated/complaints/new': typeof AuthenticatedComplaintsNewRoute
  '/_authenticated/guard/dashboard': typeof AuthenticatedGuardDashboardRoute
  '/_authenticated/resident/dashboard': typeof AuthenticatedResidentDashboardRoute
  '/_authenticated/secretary/dashboard': typeof AuthenticatedSecretaryDashboardRoute
  '/_authenticated/superadmin/dashboard': typeof AuthenticatedSuperadminDashboardRoute
  '/_authenticated/visitors/history': typeof AuthenticatedVisitorsHistoryRoute
  '/_authenticated/visitors/new': typeof AuthenticatedVisitorsNewRoute
  '/societies/$societyId/edit': typeof SocietiesSocietyIdEditRoute
  '/_authenticated/complaints/': typeof AuthenticatedComplaintsIndexRoute
  '/_authenticated/guard/visitors/new': typeof AuthenticatedGuardVisitorsNewRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/select-society'
    | '/login'
    | '/analytics'
    | '/announcements'
    | '/deliveries'
    | '/documents'
    | '/emergency'
    | '/expected-visitors'
    | '/flats'
    | '/guard'
    | '/maintenance'
    | '/notices'
    | '/payments'
    | '/profile'
    | '/public-complaints'
    | '/qr-scanner'
    | '/resident'
    | '/residents'
    | '/secretary'
    | '/settings'
    | '/staff'
    | '/superadmin'
    | '/visitor-approval'
    | '/visitor-reports'
    | '/societies/$societyId'
    | '/societies/new'
    | '/complaints/new'
    | '/guard/dashboard'
    | '/resident/dashboard'
    | '/secretary/dashboard'
    | '/superadmin/dashboard'
    | '/visitors/history'
    | '/visitors/new'
    | '/societies/$societyId/edit'
    | '/complaints/'
    | '/guard/visitors/new'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/select-society'
    | '/login'
    | '/analytics'
    | '/announcements'
    | '/deliveries'
    | '/documents'
    | '/emergency'
    | '/expected-visitors'
    | '/flats'
    | '/guard'
    | '/maintenance'
    | '/notices'
    | '/payments'
    | '/profile'
    | '/public-complaints'
    | '/qr-scanner'
    | '/resident'
    | '/residents'
    | '/secretary'
    | '/settings'
    | '/staff'
    | '/superadmin'
    | '/visitor-approval'
    | '/visitor-reports'
    | '/societies/$societyId'
    | '/societies/new'
    | '/complaints/new'
    | '/guard/dashboard'
    | '/resident/dashboard'
    | '/secretary/dashboard'
    | '/superadmin/dashboard'
    | '/visitors/history'
    | '/visitors/new'
    | '/societies/$societyId/edit'
    | '/complaints'
    | '/guard/visitors/new'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/select-society'
    | '/(auth)/login'
    | '/_authenticated/analytics'
    | '/_authenticated/announcements'
    | '/_authenticated/deliveries'
    | '/_authenticated/documents'
    | '/_authenticated/emergency'
    | '/_authenticated/expected-visitors'
    | '/_authenticated/flats'
    | '/_authenticated/guard'
    | '/_authenticated/maintenance'
    | '/_authenticated/notices'
    | '/_authenticated/payments'
    | '/_authenticated/profile'
    | '/_authenticated/public-complaints'
    | '/_authenticated/qr-scanner'
    | '/_authenticated/resident'
    | '/_authenticated/residents'
    | '/_authenticated/secretary'
    | '/_authenticated/settings'
    | '/_authenticated/staff'
    | '/_authenticated/superadmin'
    | '/_authenticated/visitor-approval'
    | '/_authenticated/visitor-reports'
    | '/societies/$societyId'
    | '/societies/new'
    | '/_authenticated/complaints/new'
    | '/_authenticated/guard/dashboard'
    | '/_authenticated/resident/dashboard'
    | '/_authenticated/secretary/dashboard'
    | '/_authenticated/superadmin/dashboard'
    | '/_authenticated/visitors/history'
    | '/_authenticated/visitors/new'
    | '/societies/$societyId/edit'
    | '/_authenticated/complaints/'
    | '/_authenticated/guard/visitors/new'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  SelectSocietyRoute: typeof SelectSocietyRoute
  authLoginRoute: typeof authLoginRoute
  SocietiesSocietyIdRoute: typeof SocietiesSocietyIdRouteWithChildren
  SocietiesNewRoute: typeof SocietiesNewRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/select-society': {
      id: '/select-society'
      path: '/select-society'
      fullPath: '/select-society'
      preLoaderRoute: typeof SelectSocietyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/login': {
      id: '/(auth)/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof authLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/analytics': {
      id: '/_authenticated/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AuthenticatedAnalyticsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/announcements': {
      id: '/_authenticated/announcements'
      path: '/announcements'
      fullPath: '/announcements'
      preLoaderRoute: typeof AuthenticatedAnnouncementsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/deliveries': {
      id: '/_authenticated/deliveries'
      path: '/deliveries'
      fullPath: '/deliveries'
      preLoaderRoute: typeof AuthenticatedDeliveriesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/documents': {
      id: '/_authenticated/documents'
      path: '/documents'
      fullPath: '/documents'
      preLoaderRoute: typeof AuthenticatedDocumentsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/emergency': {
      id: '/_authenticated/emergency'
      path: '/emergency'
      fullPath: '/emergency'
      preLoaderRoute: typeof AuthenticatedEmergencyRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/expected-visitors': {
      id: '/_authenticated/expected-visitors'
      path: '/expected-visitors'
      fullPath: '/expected-visitors'
      preLoaderRoute: typeof AuthenticatedExpectedVisitorsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/flats': {
      id: '/_authenticated/flats'
      path: '/flats'
      fullPath: '/flats'
      preLoaderRoute: typeof AuthenticatedFlatsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/guard': {
      id: '/_authenticated/guard'
      path: '/guard'
      fullPath: '/guard'
      preLoaderRoute: typeof AuthenticatedGuardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/maintenance': {
      id: '/_authenticated/maintenance'
      path: '/maintenance'
      fullPath: '/maintenance'
      preLoaderRoute: typeof AuthenticatedMaintenanceRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/notices': {
      id: '/_authenticated/notices'
      path: '/notices'
      fullPath: '/notices'
      preLoaderRoute: typeof AuthenticatedNoticesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/payments': {
      id: '/_authenticated/payments'
      path: '/payments'
      fullPath: '/payments'
      preLoaderRoute: typeof AuthenticatedPaymentsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/profile': {
      id: '/_authenticated/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AuthenticatedProfileRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/public-complaints': {
      id: '/_authenticated/public-complaints'
      path: '/public-complaints'
      fullPath: '/public-complaints'
      preLoaderRoute: typeof AuthenticatedPublicComplaintsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/qr-scanner': {
      id: '/_authenticated/qr-scanner'
      path: '/qr-scanner'
      fullPath: '/qr-scanner'
      preLoaderRoute: typeof AuthenticatedQrScannerRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/resident': {
      id: '/_authenticated/resident'
      path: '/resident'
      fullPath: '/resident'
      preLoaderRoute: typeof AuthenticatedResidentRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/residents': {
      id: '/_authenticated/residents'
      path: '/residents'
      fullPath: '/residents'
      preLoaderRoute: typeof AuthenticatedResidentsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/secretary': {
      id: '/_authenticated/secretary'
      path: '/secretary'
      fullPath: '/secretary'
      preLoaderRoute: typeof AuthenticatedSecretaryRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/staff': {
      id: '/_authenticated/staff'
      path: '/staff'
      fullPath: '/staff'
      preLoaderRoute: typeof AuthenticatedStaffRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/superadmin': {
      id: '/_authenticated/superadmin'
      path: '/superadmin'
      fullPath: '/superadmin'
      preLoaderRoute: typeof AuthenticatedSuperadminRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/visitor-approval': {
      id: '/_authenticated/visitor-approval'
      path: '/visitor-approval'
      fullPath: '/visitor-approval'
      preLoaderRoute: typeof AuthenticatedVisitorApprovalRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/visitor-reports': {
      id: '/_authenticated/visitor-reports'
      path: '/visitor-reports'
      fullPath: '/visitor-reports'
      preLoaderRoute: typeof AuthenticatedVisitorReportsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/societies/$societyId': {
      id: '/societies/$societyId'
      path: '/societies/$societyId'
      fullPath: '/societies/$societyId'
      preLoaderRoute: typeof SocietiesSocietyIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/societies/new': {
      id: '/societies/new'
      path: '/societies/new'
      fullPath: '/societies/new'
      preLoaderRoute: typeof SocietiesNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/complaints/': {
      id: '/_authenticated/complaints/'
      path: '/complaints'
      fullPath: '/complaints/'
      preLoaderRoute: typeof AuthenticatedComplaintsIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/complaints/new': {
      id: '/_authenticated/complaints/new'
      path: '/complaints/new'
      fullPath: '/complaints/new'
      preLoaderRoute: typeof AuthenticatedComplaintsNewRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/guard/dashboard': {
      id: '/_authenticated/guard/dashboard'
      path: '/dashboard'
      fullPath: '/guard/dashboard'
      preLoaderRoute: typeof AuthenticatedGuardDashboardRouteImport
      parentRoute: typeof AuthenticatedGuardRoute
    }
    '/_authenticated/resident/dashboard': {
      id: '/_authenticated/resident/dashboard'
      path: '/dashboard'
      fullPath: '/resident/dashboard'
      preLoaderRoute: typeof AuthenticatedResidentDashboardRouteImport
      parentRoute: typeof AuthenticatedResidentRoute
    }
    '/_authenticated/secretary/dashboard': {
      id: '/_authenticated/secretary/dashboard'
      path: '/dashboard'
      fullPath: '/secretary/dashboard'
      preLoaderRoute: typeof AuthenticatedSecretaryDashboardRouteImport
      parentRoute: typeof AuthenticatedSecretaryRoute
    }
    '/_authenticated/superadmin/dashboard': {
      id: '/_authenticated/superadmin/dashboard'
      path: '/dashboard'
      fullPath: '/superadmin/dashboard'
      preLoaderRoute: typeof AuthenticatedSuperadminDashboardRouteImport
      parentRoute: typeof AuthenticatedSuperadminRoute
    }
    '/_authenticated/visitors/history': {
      id: '/_authenticated/visitors/history'
      path: '/visitors/history'
      fullPath: '/visitors/history'
      preLoaderRoute: typeof AuthenticatedVisitorsHistoryRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/visitors/new': {
      id: '/_authenticated/visitors/new'
      path: '/visitors/new'
      fullPath: '/visitors/new'
      preLoaderRoute: typeof AuthenticatedVisitorsNewRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/societies/$societyId/edit': {
      id: '/societies/$societyId/edit'
      path: '/edit'
      fullPath: '/societies/$societyId/edit'
      preLoaderRoute: typeof SocietiesSocietyIdEditRouteImport
      parentRoute: typeof SocietiesSocietyIdRoute
    }
    '/_authenticated/guard/visitors/new': {
      id: '/_authenticated/guard/visitors/new'
      path: '/visitors/new'
      fullPath: '/guard/visitors/new'
      preLoaderRoute: typeof AuthenticatedGuardVisitorsNewRouteImport
      parentRoute: typeof AuthenticatedGuardRoute
    }
  }
}

interface AuthenticatedGuardRouteChildren {
  AuthenticatedGuardDashboardRoute: typeof AuthenticatedGuardDashboardRoute
  AuthenticatedGuardVisitorsNewRoute: typeof AuthenticatedGuardVisitorsNewRoute
}

const AuthenticatedGuardRouteChildren: AuthenticatedGuardRouteChildren = {
  AuthenticatedGuardDashboardRoute: AuthenticatedGuardDashboardRoute,
  AuthenticatedGuardVisitorsNewRoute: AuthenticatedGuardVisitorsNewRoute,
}

const AuthenticatedGuardRouteWithChildren =
  AuthenticatedGuardRoute._addFileChildren(AuthenticatedGuardRouteChildren)

interface AuthenticatedResidentRouteChildren {
  AuthenticatedResidentDashboardRoute: typeof AuthenticatedResidentDashboardRoute
}

const AuthenticatedResidentRouteChildren: AuthenticatedResidentRouteChildren = {
  AuthenticatedResidentDashboardRoute: AuthenticatedResidentDashboardRoute,
}

const AuthenticatedResidentRouteWithChildren =
  AuthenticatedResidentRoute._addFileChildren(
    AuthenticatedResidentRouteChildren,
  )

interface AuthenticatedSecretaryRouteChildren {
  AuthenticatedSecretaryDashboardRoute: typeof AuthenticatedSecretaryDashboardRoute
}

const AuthenticatedSecretaryRouteChildren: AuthenticatedSecretaryRouteChildren =
  {
    AuthenticatedSecretaryDashboardRoute: AuthenticatedSecretaryDashboardRoute,
  }

const AuthenticatedSecretaryRouteWithChildren =
  AuthenticatedSecretaryRoute._addFileChildren(
    AuthenticatedSecretaryRouteChildren,
  )

interface AuthenticatedSuperadminRouteChildren {
  AuthenticatedSuperadminDashboardRoute: typeof AuthenticatedSuperadminDashboardRoute
}

const AuthenticatedSuperadminRouteChildren: AuthenticatedSuperadminRouteChildren =
  {
    AuthenticatedSuperadminDashboardRoute:
      AuthenticatedSuperadminDashboardRoute,
  }

const AuthenticatedSuperadminRouteWithChildren =
  AuthenticatedSuperadminRoute._addFileChildren(
    AuthenticatedSuperadminRouteChildren,
  )

interface AuthenticatedRouteChildren {
  AuthenticatedAnalyticsRoute: typeof AuthenticatedAnalyticsRoute
  AuthenticatedAnnouncementsRoute: typeof AuthenticatedAnnouncementsRoute
  AuthenticatedDeliveriesRoute: typeof AuthenticatedDeliveriesRoute
  AuthenticatedDocumentsRoute: typeof AuthenticatedDocumentsRoute
  AuthenticatedEmergencyRoute: typeof AuthenticatedEmergencyRoute
  AuthenticatedExpectedVisitorsRoute: typeof AuthenticatedExpectedVisitorsRoute
  AuthenticatedFlatsRoute: typeof AuthenticatedFlatsRoute
  AuthenticatedGuardRoute: typeof AuthenticatedGuardRouteWithChildren
  AuthenticatedMaintenanceRoute: typeof AuthenticatedMaintenanceRoute
  AuthenticatedNoticesRoute: typeof AuthenticatedNoticesRoute
  AuthenticatedPaymentsRoute: typeof AuthenticatedPaymentsRoute
  AuthenticatedProfileRoute: typeof AuthenticatedProfileRoute
  AuthenticatedPublicComplaintsRoute: typeof AuthenticatedPublicComplaintsRoute
  AuthenticatedQrScannerRoute: typeof AuthenticatedQrScannerRoute
  AuthenticatedResidentRoute: typeof AuthenticatedResidentRouteWithChildren
  AuthenticatedResidentsRoute: typeof AuthenticatedResidentsRoute
  AuthenticatedSecretaryRoute: typeof AuthenticatedSecretaryRouteWithChildren
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
  AuthenticatedStaffRoute: typeof AuthenticatedStaffRoute
  AuthenticatedSuperadminRoute: typeof AuthenticatedSuperadminRouteWithChildren
  AuthenticatedVisitorApprovalRoute: typeof AuthenticatedVisitorApprovalRoute
  AuthenticatedVisitorReportsRoute: typeof AuthenticatedVisitorReportsRoute
  AuthenticatedComplaintsNewRoute: typeof AuthenticatedComplaintsNewRoute
  AuthenticatedVisitorsHistoryRoute: typeof AuthenticatedVisitorsHistoryRoute
  AuthenticatedVisitorsNewRoute: typeof AuthenticatedVisitorsNewRoute
  AuthenticatedComplaintsIndexRoute: typeof AuthenticatedComplaintsIndexRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAnalyticsRoute: AuthenticatedAnalyticsRoute,
  AuthenticatedAnnouncementsRoute: AuthenticatedAnnouncementsRoute,
  AuthenticatedDeliveriesRoute: AuthenticatedDeliveriesRoute,
  AuthenticatedDocumentsRoute: AuthenticatedDocumentsRoute,
  AuthenticatedEmergencyRoute: AuthenticatedEmergencyRoute,
  AuthenticatedExpectedVisitorsRoute: AuthenticatedExpectedVisitorsRoute,
  AuthenticatedFlatsRoute: AuthenticatedFlatsRoute,
  AuthenticatedGuardRoute: AuthenticatedGuardRouteWithChildren,
  AuthenticatedMaintenanceRoute: AuthenticatedMaintenanceRoute,
  AuthenticatedNoticesRoute: AuthenticatedNoticesRoute,
  AuthenticatedPaymentsRoute: AuthenticatedPaymentsRoute,
  AuthenticatedProfileRoute: AuthenticatedProfileRoute,
  AuthenticatedPublicComplaintsRoute: AuthenticatedPublicComplaintsRoute,
  AuthenticatedQrScannerRoute: AuthenticatedQrScannerRoute,
  AuthenticatedResidentRoute: AuthenticatedResidentRouteWithChildren,
  AuthenticatedResidentsRoute: AuthenticatedResidentsRoute,
  AuthenticatedSecretaryRoute: AuthenticatedSecretaryRouteWithChildren,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
  AuthenticatedStaffRoute: AuthenticatedStaffRoute,
  AuthenticatedSuperadminRoute: AuthenticatedSuperadminRouteWithChildren,
  AuthenticatedVisitorApprovalRoute: AuthenticatedVisitorApprovalRoute,
  AuthenticatedVisitorReportsRoute: AuthenticatedVisitorReportsRoute,
  AuthenticatedComplaintsNewRoute: AuthenticatedComplaintsNewRoute,
  AuthenticatedVisitorsHistoryRoute: AuthenticatedVisitorsHistoryRoute,
  AuthenticatedVisitorsNewRoute: AuthenticatedVisitorsNewRoute,
  AuthenticatedComplaintsIndexRoute: AuthenticatedComplaintsIndexRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

interface SocietiesSocietyIdRouteChildren {
  SocietiesSocietyIdEditRoute: typeof SocietiesSocietyIdEditRoute
}

const SocietiesSocietyIdRouteChildren: SocietiesSocietyIdRouteChildren = {
  SocietiesSocietyIdEditRoute: SocietiesSocietyIdEditRoute,
}

const SocietiesSocietyIdRouteWithChildren =
  SocietiesSocietyIdRoute._addFileChildren(SocietiesSocietyIdRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  SelectSocietyRoute: SelectSocietyRoute,
  authLoginRoute: authLoginRoute,
  SocietiesSocietyIdRoute: SocietiesSocietyIdRouteWithChildren,
  SocietiesNewRoute: SocietiesNewRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.jsx'
import type { startInstance } from './start.js'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
