/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from "./routes/__root";
import { Route as IndexRouteImport } from "./routes/index";
import { Route as AuthenticatedRouteImport } from "./routes/_authenticated";
import { Route as SelectSocietyRouteImport } from "./routes/select-society";
import { Route as authLoginRouteImport } from "./routes/(auth)/login";
import { Route as AuthenticatedAnalyticsRouteImport } from "./routes/_authenticated.analytics";
import { Route as AuthenticatedAnnouncementsRouteImport } from "./routes/_authenticated.announcements";
import { Route as AuthenticatedDeliveriesRouteImport } from "./routes/_authenticated.deliveries";
import { Route as AuthenticatedDocumentsRouteImport } from "./routes/_authenticated.documents";
import { Route as AuthenticatedEmergencyRouteImport } from "./routes/_authenticated.emergency";
import { Route as AuthenticatedExpectedVisitorsRouteImport } from "./routes/_authenticated.expected-visitors";
import { Route as AuthenticatedFlatsRouteImport } from "./routes/_authenticated.flats";
import { Route as AuthenticatedGuardRouteImport } from "./routes/_authenticated.guard";
import { Route as AuthenticatedMaintenanceRouteImport } from "./routes/_authenticated.maintenance";
import { Route as AuthenticatedNoticesRouteImport } from "./routes/_authenticated.notices";
import { Route as AuthenticatedPaymentsRouteImport } from "./routes/_authenticated.payments";
import { Route as AuthenticatedProfileRouteImport } from "./routes/_authenticated.profile";
import { Route as AuthenticatedPublicComplaintsRouteImport } from "./routes/_authenticated.public-complaints";
import { Route as AuthenticatedQrScannerRouteImport } from "./routes/_authenticated.qr-scanner";
import { Route as AuthenticatedResidentRouteImport } from "./routes/_authenticated.resident";
import { Route as AuthenticatedResidentsRouteImport } from "./routes/_authenticated.residents";
import { Route as AuthenticatedSecretaryRouteImport } from "./routes/_authenticated.secretary";
import { Route as AuthenticatedSettingsRouteImport } from "./routes/_authenticated.settings";
import { Route as AuthenticatedStaffRouteImport } from "./routes/_authenticated.staff";
import { Route as AuthenticatedSuperadminRouteImport } from "./routes/_authenticated.superadmin";
import { Route as AuthenticatedVisitorApprovalRouteImport } from "./routes/_authenticated.visitor-approval";
import { Route as AuthenticatedVisitorReportsRouteImport } from "./routes/_authenticated.visitor-reports";
import { Route as SocietiesSocietyIdRouteImport } from "./routes/societies.$societyId";
import { Route as SocietiesNewRouteImport } from "./routes/societies.new";
import { Route as AuthenticatedComplaintsIndexRouteImport } from "./routes/_authenticated.complaints.index";
import { Route as AuthenticatedComplaintsNewRouteImport } from "./routes/_authenticated.complaints.new";
import { Route as AuthenticatedGuardDashboardRouteImport } from "./routes/_authenticated.guard.dashboard";
import { Route as AuthenticatedResidentDashboardRouteImport } from "./routes/_authenticated.resident.dashboard";
import { Route as AuthenticatedSecretaryDashboardRouteImport } from "./routes/_authenticated.secretary.dashboard";
import { Route as AuthenticatedSuperadminDashboardRouteImport } from "./routes/_authenticated.superadmin.dashboard";
import { Route as AuthenticatedVisitorsHistoryRouteImport } from "./routes/_authenticated.visitors.history";
import { Route as AuthenticatedVisitorsNewRouteImport } from "./routes/_authenticated.visitors.new";
import { Route as SocietiesSocietyIdEditRouteImport } from "./routes/societies.$societyId.edit";
import { Route as AuthenticatedGuardVisitorsNewRouteImport } from "./routes/_authenticated.guard.visitors.new";

const IndexRoute = IndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => rootRouteImport,
});
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: "/_authenticated",
  getParentRoute: () => rootRouteImport,
});
const SelectSocietyRoute = SelectSocietyRouteImport.update({
  id: "/select-society",
  path: "/select-society",
  getParentRoute: () => rootRouteImport,
});
const authLoginRoute = authLoginRouteImport.update({
  id: "/(auth)/login",
  path: "/login",
  getParentRoute: () => rootRouteImport,
});
const AuthenticatedAnalyticsRoute = AuthenticatedAnalyticsRouteImport.update({
  id: "/analytics",
  path: "/analytics",
  getParentRoute: () => AuthenticatedRoute,
});
const AuthenticatedAnnouncementsRoute = AuthenticatedAnnouncementsRouteImport.update({
  id: "/announcements",
  path: "/announcements",
  getParentRoute: () => AuthenticatedRoute,
});
const AuthenticatedDeliveriesRoute = AuthenticatedDeliveriesRouteImport.update({
  id: "/deliveries",
  path: "/deliveries",
  getParentRoute: () => AuthenticatedRoute,
});
const AuthenticatedDocumentsRoute = AuthenticatedDocumentsRouteImport.update({
  id: "/documents",
  path: "/documents",
  getParentRoute: () => AuthenticatedRoute,
});
const AuthenticatedEmergencyRoute = AuthenticatedEmergencyRouteImport.update({
  id: "/emergency",
  path: "/emergency",
  getParentRoute: () => AuthenticatedRoute,
});
const AuthenticatedExpectedVisitorsRoute = AuthenticatedExpectedVisitorsRouteImport.update({
  id: "/expected-visitors",
  path: "/expected-visitors",
  getParentRoute: () => AuthenticatedRoute,
});
const AuthenticatedFlatsRoute = AuthenticatedFlatsRouteImport.update({
  id: "/flats",
  path: "/flats",
  getParentRoute: () => AuthenticatedRoute,
});
const AuthenticatedGuardRoute = AuthenticatedGuardRouteImport.update({
  id: "/guard",
  path: "/guard",
  getParentRoute: () => AuthenticatedRoute,
});
const AuthenticatedMaintenanceRoute = AuthenticatedMaintenanceRouteImport.update({
  id: "/maintenance",
  path: "/maintenance",
  getParentRoute: () => AuthenticatedRoute,
});
const AuthenticatedNoticesRoute = AuthenticatedNoticesRouteImport.update({
  id: "/notices",
  path: "/notices",
  getParentRoute: () => AuthenticatedRoute,
});
const AuthenticatedPaymentsRoute = AuthenticatedPaymentsRouteImport.update({
  id: "/payments",
  path: "/payments",
  getParentRoute: () => AuthenticatedRoute,
});
const AuthenticatedProfileRoute = AuthenticatedProfileRouteImport.update({
  id: "/profile",
  path: "/profile",
  getParentRoute: () => AuthenticatedRoute,
});
const AuthenticatedPublicComplaintsRoute = AuthenticatedPublicComplaintsRouteImport.update({
  id: "/public-complaints",
  path: "/public-complaints",
  getParentRoute: () => AuthenticatedRoute,
});
const AuthenticatedQrScannerRoute = AuthenticatedQrScannerRouteImport.update({
  id: "/qr-scanner",
  path: "/qr-scanner",
  getParentRoute: () => AuthenticatedRoute,
});
const AuthenticatedResidentRoute = AuthenticatedResidentRouteImport.update({
  id: "/resident",
  path: "/resident",
  getParentRoute: () => AuthenticatedRoute,
});
const AuthenticatedResidentsRoute = AuthenticatedResidentsRouteImport.update({
  id: "/residents",
  path: "/residents",
  getParentRoute: () => AuthenticatedRoute,
});
const AuthenticatedSecretaryRoute = AuthenticatedSecretaryRouteImport.update({
  id: "/secretary",
  path: "/secretary",
  getParentRoute: () => AuthenticatedRoute,
});
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: "/settings",
  path: "/settings",
  getParentRoute: () => AuthenticatedRoute,
});
const AuthenticatedStaffRoute = AuthenticatedStaffRouteImport.update({
  id: "/staff",
  path: "/staff",
  getParentRoute: () => AuthenticatedRoute,
});
const AuthenticatedSuperadminRoute = AuthenticatedSuperadminRouteImport.update({
  id: "/superadmin",
  path: "/superadmin",
  getParentRoute: () => AuthenticatedRoute,
});
const AuthenticatedVisitorApprovalRoute = AuthenticatedVisitorApprovalRouteImport.update({
  id: "/visitor-approval",
  path: "/visitor-approval",
  getParentRoute: () => AuthenticatedRoute,
});
const AuthenticatedVisitorReportsRoute = AuthenticatedVisitorReportsRouteImport.update({
  id: "/visitor-reports",
  path: "/visitor-reports",
  getParentRoute: () => AuthenticatedRoute,
});
const SocietiesSocietyIdRoute = SocietiesSocietyIdRouteImport.update({
  id: "/societies/$societyId",
  path: "/societies/$societyId",
  getParentRoute: () => rootRouteImport,
});
const SocietiesNewRoute = SocietiesNewRouteImport.update({
  id: "/societies/new",
  path: "/societies/new",
  getParentRoute: () => rootRouteImport,
});
const AuthenticatedComplaintsIndexRoute = AuthenticatedComplaintsIndexRouteImport.update({
  id: "/complaints/",
  path: "/complaints/",
  getParentRoute: () => AuthenticatedRoute,
});
const AuthenticatedComplaintsNewRoute = AuthenticatedComplaintsNewRouteImport.update({
  id: "/complaints/new",
  path: "/complaints/new",
  getParentRoute: () => AuthenticatedRoute,
});
const AuthenticatedGuardDashboardRoute = AuthenticatedGuardDashboardRouteImport.update({
  id: "/dashboard",
  path: "/dashboard",
  getParentRoute: () => AuthenticatedGuardRoute,
});
const AuthenticatedResidentDashboardRoute = AuthenticatedResidentDashboardRouteImport.update({
  id: "/dashboard",
  path: "/dashboard",
  getParentRoute: () => AuthenticatedResidentRoute,
});
const AuthenticatedSecretaryDashboardRoute = AuthenticatedSecretaryDashboardRouteImport.update({
  id: "/dashboard",
  path: "/dashboard",
  getParentRoute: () => AuthenticatedSecretaryRoute,
});
const AuthenticatedSuperadminDashboardRoute = AuthenticatedSuperadminDashboardRouteImport.update({
  id: "/dashboard",
  path: "/dashboard",
  getParentRoute: () => AuthenticatedSuperadminRoute,
});
const AuthenticatedVisitorsHistoryRoute = AuthenticatedVisitorsHistoryRouteImport.update({
  id: "/visitors/history",
  path: "/visitors/history",
  getParentRoute: () => AuthenticatedRoute,
});
const AuthenticatedVisitorsNewRoute = AuthenticatedVisitorsNewRouteImport.update({
  id: "/visitors/new",
  path: "/visitors/new",
  getParentRoute: () => AuthenticatedRoute,
});
const SocietiesSocietyIdEditRoute = SocietiesSocietyIdEditRouteImport.update({
  id: "/edit",
  path: "/edit",
  getParentRoute: () => SocietiesSocietyIdRoute,
});
const AuthenticatedGuardVisitorsNewRoute = AuthenticatedGuardVisitorsNewRouteImport.update({
  id: "/visitors/new",
  path: "/visitors/new",
  getParentRoute: () => AuthenticatedGuardRoute,
});

const AuthenticatedGuardRouteChildren = {
  AuthenticatedGuardDashboardRoute: AuthenticatedGuardDashboardRoute,
  AuthenticatedGuardVisitorsNewRoute: AuthenticatedGuardVisitorsNewRoute,
};

const AuthenticatedGuardRouteWithChildren = AuthenticatedGuardRoute._addFileChildren(
  AuthenticatedGuardRouteChildren,
);

const AuthenticatedResidentRouteChildren = {
  AuthenticatedResidentDashboardRoute: AuthenticatedResidentDashboardRoute,
};

const AuthenticatedResidentRouteWithChildren = AuthenticatedResidentRoute._addFileChildren(
  AuthenticatedResidentRouteChildren,
);

const AuthenticatedSecretaryRouteChildren = {
  AuthenticatedSecretaryDashboardRoute: AuthenticatedSecretaryDashboardRoute,
};

const AuthenticatedSecretaryRouteWithChildren = AuthenticatedSecretaryRoute._addFileChildren(
  AuthenticatedSecretaryRouteChildren,
);

const AuthenticatedSuperadminRouteChildren = {
  AuthenticatedSuperadminDashboardRoute: AuthenticatedSuperadminDashboardRoute,
};

const AuthenticatedSuperadminRouteWithChildren = AuthenticatedSuperadminRoute._addFileChildren(
  AuthenticatedSuperadminRouteChildren,
);

const AuthenticatedRouteChildren = {
  AuthenticatedAnalyticsRoute: AuthenticatedAnalyticsRoute,
  AuthenticatedAnnouncementsRoute: AuthenticatedAnnouncementsRoute,
  AuthenticatedDeliveriesRoute: AuthenticatedDeliveriesRoute,
  AuthenticatedDocumentsRoute: AuthenticatedDocumentsRoute,
  AuthenticatedEmergencyRoute: AuthenticatedEmergencyRoute,
  AuthenticatedExpectedVisitorsRoute: AuthenticatedExpectedVisitorsRoute,
  AuthenticatedFlatsRoute: AuthenticatedFlatsRoute,
  AuthenticatedGuardRoute: AuthenticatedGuardRouteWithChildren,
  AuthenticatedMaintenanceRoute: AuthenticatedMaintenanceRoute,
  AuthenticatedNoticesRoute: AuthenticatedNoticesRoute,
  AuthenticatedPaymentsRoute: AuthenticatedPaymentsRoute,
  AuthenticatedProfileRoute: AuthenticatedProfileRoute,
  AuthenticatedPublicComplaintsRoute: AuthenticatedPublicComplaintsRoute,
  AuthenticatedQrScannerRoute: AuthenticatedQrScannerRoute,
  AuthenticatedResidentRoute: AuthenticatedResidentRouteWithChildren,
  AuthenticatedResidentsRoute: AuthenticatedResidentsRoute,
  AuthenticatedSecretaryRoute: AuthenticatedSecretaryRouteWithChildren,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
  AuthenticatedStaffRoute: AuthenticatedStaffRoute,
  AuthenticatedSuperadminRoute: AuthenticatedSuperadminRouteWithChildren,
  AuthenticatedVisitorApprovalRoute: AuthenticatedVisitorApprovalRoute,
  AuthenticatedVisitorReportsRoute: AuthenticatedVisitorReportsRoute,
  AuthenticatedComplaintsNewRoute: AuthenticatedComplaintsNewRoute,
  AuthenticatedVisitorsHistoryRoute: AuthenticatedVisitorsHistoryRoute,
  AuthenticatedVisitorsNewRoute: AuthenticatedVisitorsNewRoute,
  AuthenticatedComplaintsIndexRoute: AuthenticatedComplaintsIndexRoute,
};

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
);

const SocietiesSocietyIdRouteChildren = {
  SocietiesSocietyIdEditRoute: SocietiesSocietyIdEditRoute,
};

const SocietiesSocietyIdRouteWithChildren = SocietiesSocietyIdRoute._addFileChildren(
  SocietiesSocietyIdRouteChildren,
);

const rootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  SelectSocietyRoute: SelectSocietyRoute,
  authLoginRoute: authLoginRoute,
  SocietiesSocietyIdRoute: SocietiesSocietyIdRouteWithChildren,
  SocietiesNewRoute: SocietiesNewRoute,
};
export const routeTree = rootRouteImport._addFileChildren(rootRouteChildren)._addFileTypes();
